In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("Consumption (2).xlsx")

In [4]:
df.head(5)

,Country,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Australia,0.984272,2.373425,1.904745,2.159658,4.413741,3.381946,2.871492,5.127316,5.562127,...,2.019693,2.299227,2.598145,2.669282,2.472382,2.821450,1.694241,-3.274079,0.720412,4.301009
1,France,0.653260,1.124522,-0.058178,1.675137,1.722185,1.960316,0.538042,3.985687,3.463975,...,0.509561,0.819662,1.479019,1.779880,1.478663,0.982171,1.768661,-6.615097,5.136997,2.297100
2,Malaysia,9.045416,4.653667,6.252972,9.389146,11.657272,6.865008,4.310064,-10.235818,2.859895,...,7.248948,6.976394,6.017542,5.851186,6.908266,7.979937,7.687682,-3.944784,1.788309,11.413662
3,Philippines,2.498832,3.236732,2.528019,2.914994,2.985639,3.820330,4.332885,5.292290,4.028264,...,5.819003,5.784455,6.444572,7.149608,5.957367,5.765216,5.866915,-7.956529,4.211487,8.288528
4,Thailand,5.421469,8.697928,8.418805,7.875917,8.279274,5.033393,-1.410175,-10.199664,4.066022,...,0.954079,0.533204,2.604257,2.880873,3.087908,4.574110,3.965830,-0.781192,0.603338,6.176202

In [4]:
print(df.columns)

Index(['Country',      1991,      1992,      1993,      1994,      1995,
            1996,      1997,      1998,      1999,      2000,      2001,
            2002,      2003,      2004,      2005,      2006,      2007,
            2008,      2009,      2010,      2011,      2012,      2013,
            2014,      2015,      2016,      2017,      2018,      2019,
            2020,      2021,      2022],
      dtype='object')

In [5]:
df_long = df.melt(
    id_vars=['Country'],
    value_vars=[year for year in range(1991, 2023)], 
    var_name='Year',
    value_name='Consumption'
)

In [6]:
df_long.tail()

           Country  Year  Consumption
187         France  2022     2.297100
188       Malaysia  2022    11.413662
189    Philippines  2022     8.288528
190       Thailand  2022     6.176202
191  United States  2022     2.531839

In [6]:
df_long.to_csv("real_final_Consumption.csv",index=False)

In [8]:
df2 = pd.read_excel("Inflation (2).xlsx")

In [9]:
df2.head()

,Country,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Australia,3.176675,1.012231,1.753653,1.969635,4.627767,2.615385,0.224888,0.860135,1.483129,...,2.449889,2.487923,1.508367,1.276991,1.948647,1.911401,1.610768,0.846906,2.863910,6.594097
1,France,3.213407,2.363760,2.104463,1.655515,1.796481,1.982884,1.203943,0.651127,0.537142,...,0.863715,0.507759,0.037514,0.183335,1.032283,1.850815,1.108255,0.476499,1.642331,5.222367
2,Malaysia,4.358333,4.767228,3.536585,3.724971,3.450575,3.488559,2.662515,5.270342,2.744561,...,2.105012,3.142991,2.104390,2.090567,3.871201,0.884709,0.662892,-1.138702,2.477102,3.378699
3,Philippines,19.261459,8.651004,6.716311,10.386473,6.831996,7.476104,5.590259,9.234934,5.939049,...,2.582688,3.597823,0.674193,1.253699,2.853188,5.309347,2.392065,2.393162,3.927180,5.821158
4,Thailand,5.709853,4.139146,3.312192,5.047749,5.818182,5.805106,5.625797,7.994729,0.284726,...,2.184886,1.895142,-0.900425,0.188150,0.665632,1.063898,0.706729,-0.845937,1.230395,-1.610680

In [10]:
df2.columns

Index(['Country ',       1991,       1992,       1993,       1994,       1995,
             1996,       1997,       1998,       1999,       2000,       2001,
             2002,       2003,       2004,       2005,       2006,       2007,
             2008,       2009,       2010,       2011,       2012,       2013,
             2014,       2015,       2016,       2017,       2018,       2019,
             2020,       2021,       2022],
      dtype='object')

In [11]:
df2= df2.rename(columns={"Country ":"Country"})

In [12]:
df.columns

Index(['Country',      1991,      1992,      1993,      1994,      1995,
            1996,      1997,      1998,      1999,      2000,      2001,
            2002,      2003,      2004,      2005,      2006,      2007,
            2008,      2009,      2010,      2011,      2012,      2013,
            2014,      2015,      2016,      2017,      2018,      2019,
            2020,      2021,      2022],
      dtype='object')

In [13]:
df2_long = df2.melt(
    id_vars=["Country"],
    value_vars=list(range(1991, 2023)),
    var_name="Year",
    value_name="Inflation"
)

In [14]:
df2_long.head()

       Country  Year  Inflation
0    Australia  1991   3.176675
1       France  1991   3.213407
2     Malaysia  1991   4.358333
3  Philippines  1991  19.261459
4     Thailand  1991   5.709853

In [15]:
df2_long.tail()

           Country  Year  Inflation
187         France  2022   5.222367
188       Malaysia  2022   3.378699
189    Philippines  2022   5.821158
190       Thailand  2022  -1.610680
191  United States  2022   8.002800

In [16]:
df2_long.to_csv("real_final__Inflation.csv",index=False)

In [17]:
df3 = pd.read_excel("GDP (2).xlsx")

In [18]:
df3.head()

,Country,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Australia,36366.696240,36117.544650,37246.004433,38356.769198,39407.564753,40437.094186,41569.165368,43081.720172,44755.659972,...,55966.150927,56571.806252,56970.361303,57632.999593,57991.771347,58772.706315,59181.299790,58377.767052,59465.535671,61200.458896
1,France,28197.235954,28482.519468,28257.096249,28822.500650,29379.615842,29683.778607,30325.522872,31256.507383,32152.720748,...,36256.086681,36444.394909,36702.432373,36920.534285,37580.597933,38062.443596,38705.207294,35709.204593,38030.857169,38868.330333
2,Malaysia,4456.931331,4726.137892,5062.591104,5390.101676,5771.352120,6190.464291,6480.556495,5857.967029,6070.956220,...,8964.807249,9341.730560,9648.679794,9901.479602,10293.762921,10610.195024,10902.983486,10171.465784,10388.266712,11191.651176
3,Philippines,1656.383497,1624.349398,1620.355058,1654.746139,1693.808731,1752.238001,1800.259131,1746.525905,1759.421052,...,2654.415069,2776.920059,2909.858180,3076.337419,3247.450388,3410.936480,3575.881709,3198.666900,3350.975876,3577.701366
4,Thailand,2810.567020,2989.853854,3186.997071,3391.489866,3614.932440,3766.863644,3614.608485,3295.360184,3403.087374,...,5516.611642,5541.465994,5688.853354,5857.780529,6076.743077,6314.199484,6434.537705,6035.186277,6121.526965,6278.785514

In [19]:
df3_long = df3.melt(
    id_vars=['Country'],
    value_vars=[year for year in range(1991, 2023)],
    var_name='Year',
    value_name='GDP_per_capita'
)

In [20]:
df3_long.head()

       Country  Year  GDP_per_capita
0    Australia  1991    36366.696240
1       France  1991    28197.235954
2     Malaysia  1991     4456.931331
3  Philippines  1991     1656.383497
4     Thailand  1991     2810.567020

In [21]:
df3_long.to_csv("real_final_GDP_per_capita.csv",index=False)

In [22]:
df4 = pd.read_excel("Unemployment (2).xlsx")

In [23]:
df4.head()

,Country,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Australia,9.586,10.733,10.879,9.724,8.473,8.509,8.367,7.684,6.876,...,5.663,6.078,6.055,5.711,5.592,5.345,5.143,6.394,5.022,3.728
1,France,9.134,10.203,11.320,12.593,11.834,12.367,12.566,12.074,11.981,...,9.913,10.273,10.354,10.057,9.409,9.018,8.415,8.009,7.871,7.303
2,Malaysia,3.700,3.710,4.110,3.640,3.150,2.520,2.450,3.200,3.430,...,3.140,2.880,3.100,3.440,3.410,3.300,3.330,4.540,4.640,3.930
3,Philippines,3.727,3.849,3.869,3.767,3.680,3.607,3.592,3.697,3.751,...,3.497,3.600,3.068,2.695,2.552,2.338,2.237,2.522,3.398,2.598
4,Thailand,2.630,1.350,1.490,1.347,1.100,1.071,0.873,3.404,2.968,...,0.249,0.576,0.597,0.688,0.830,0.765,0.716,1.099,1.215,0.940

In [24]:
df4_long = df4.melt(
    id_vars=['Country'],
    value_vars=[year for year in range(1991, 2023)],
    var_name='Year',
    value_name='Unemployment_rate'
)

In [25]:
df4_long.head()

       Country  Year  Unemployment_rate
0    Australia  1991              9.586
1       France  1991              9.134
2     Malaysia  1991              3.700
3  Philippines  1991              3.727
4     Thailand  1991              2.630

In [26]:
df4_long.to_csv("real_final_Unemployment_rate.csv",index=False)

In [27]:
df5= pd.read_excel("Exchange (2).xlsx")

In [28]:
df5.head()

,Country,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Australia,1.283756,1.361648,1.470560,1.367751,1.349033,1.277863,1.347380,1.591828,1.549950,...,1.035843,1.109363,1.331090,1.345214,1.304758,1.338412,1.438507,1.453085,1.331224,1.441664
1,France,5.642117,5.293816,5.663230,5.552045,4.991483,5.115522,5.836692,5.899516,0.938283,...,0.752945,0.752728,0.901296,0.903421,0.885206,0.846773,0.893276,0.875506,0.845494,0.949624
2,Malaysia,2.750067,2.547383,2.574095,2.624257,2.504404,2.515942,2.813192,3.924375,3.800000,...,3.150909,3.272860,3.905500,4.148301,4.300441,4.035130,4.142470,4.203482,4.143298,4.401076
3,Philippines,27.478633,25.512492,27.119842,26.417167,25.714467,26.216100,29.470658,40.893050,39.088983,...,42.446185,44.395154,45.502840,47.492464,50.403720,52.661430,51.795783,49.624096,49.254598,54.477786
4,Thailand,25.516795,25.400128,25.319611,25.149952,24.915176,25.342683,31.364334,41.359387,37.813656,...,30.725967,32.479833,34.247717,35.296383,33.939811,32.310226,31.047606,31.293673,31.977093,35.061350

In [29]:
df5_long = df5.melt(
    id_vars=['Country'],
    value_vars=[year for year in range(1991, 2023)],
    var_name='Year',
    value_name='ExchangeRate'
)

In [30]:
df5_long.head()

       Country  Year  ExchangeRate
0    Australia  1991      1.283756
1       France  1991      5.642117
2     Malaysia  1991      2.750067
3  Philippines  1991     27.478633
4     Thailand  1991     25.516795

In [31]:
df5_long.to_csv("real_final_Exchange_Rate.csv",index=False)

In [32]:
df6= pd.read_excel("Saving.xlsx")

In [50]:
df6.tail()

,Country,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,France,23.203779,22.546309,21.296109,21.398103,21.972967,21.790399,22.757644,23.705706,24.289651,...,21.152730,21.092207,21.531098,21.160725,21.618517,21.890006,23.489990,20.783586,23.451947,22.490312
2,Malaysia,29.278262,31.696475,34.713172,35.091416,33.893255,37.040723,37.020545,39.849159,38.305981,...,29.419840,29.366567,28.399148,28.385002,28.335988,26.128325,24.546151,23.821061,26.009961,26.780779
3,Philippines,20.994026,20.710067,20.351273,22.420907,21.935133,22.406747,23.912234,29.619158,35.967801,...,36.354402,37.347448,35.634833,35.054772,35.488632,33.807051,31.755187,24.818173,20.202919,22.473718
4,Thailand,34.528016,34.019905,35.940379,35.802707,35.802812,34.603520,32.254598,31.743745,30.455238,...,27.220767,27.485079,28.043824,30.076504,31.942467,31.686585,31.515506,28.042922,27.464683,26.308404
5,United States,18.814189,17.688025,17.051004,17.861705,18.758937,19.651123,20.847652,21.390497,20.926098,...,18.604640,19.721013,19.794721,18.667694,19.110375,19.346554,19.574167,18.643384,18.032934,18.692764

In [51]:
df6_long = df6.melt(
    id_vars=['Country'],
    value_vars=[year for year in range(1991, 2023)],
    var_name='Year',
    value_name='GrossSaving'
)

In [52]:
print(df6_long.head())

       Country  Year  GrossSaving
0    Australia  1991    20.807872
1       France  1991    23.203779
2     Malaysia  1991    29.278262
3  Philippines  1991    20.994026
4     Thailand  1991    34.528016

In [53]:
print(df6_long.tail())

           Country  Year  GrossSaving
187         France  2022    22.490312
188       Malaysia  2022    26.780779
189    Philippines  2022    22.473718
190       Thailand  2022    26.308404
191  United States  2022    18.692764

In [54]:
df6_long.to_csv("real_final_GrossSaving.csv",index=False)

In [55]:
consumption = pd.read_csv("real_final_Consumption.csv")
inflation = pd.read_csv("real_final__Inflation.csv")
gdp = pd.read_csv("real_final_GDP_per_capita.csv")
unemployment = pd.read_csv("real_final_Unemployment_rate.csv")
exchange = pd.read_csv("real_final_Exchange_Rate.csv")
saving = pd.read_csv("real_final_GrossSaving.csv")

In [56]:
real_final_df = consumption.merge(inflation,on=["Country","Year"])

In [57]:
real_final_df.tail()

           Country  Year  Consumption  Inflation
187         France  2022     2.297100   5.222367
188       Malaysia  2022    11.413662   3.378699
189    Philippines  2022     8.288528   5.821158
190       Thailand  2022     6.176202  -1.610680
191  United States  2022     2.531839   8.002800

In [58]:
real_final_df=real_final_df.merge(gdp,on=["Country","Year"])

In [59]:
real_final_df=real_final_df.merge(unemployment,on=["Country","Year"])

In [60]:
real_final_df=real_final_df.merge(exchange,on=["Country","Year"])

In [61]:
real_final_df=real_final_df.merge(saving,on=["Country","Year"])

In [62]:
real_final_df.head()

,Country,Year,Consumption,Inflation,GDP_per_capita,Unemployment_rate,ExchangeRate,GrossSaving
0,Australia,1991,0.984272,3.176675,36366.696240,9.586,1.283756,20.807872
1,France,1991,0.653260,3.213407,28197.235954,9.134,5.642117,23.203779
2,Malaysia,1991,9.045416,4.358333,4456.931331,3.700,2.750067,29.278262
3,Philippines,1991,2.498832,19.261459,1656.383497,3.727,27.478633,20.994026
4,Thailand,1991,5.421469,5.709853,2810.567020,2.630,25.516795,34.528016

In [63]:
real_final_df.tail()

,Country,Year,Consumption,Inflation,GDP_per_capita,Unemployment_rate,ExchangeRate,GrossSaving
187,France,2022,2.297100,5.222367,38868.330333,7.303,0.949624,22.490312
188,Malaysia,2022,11.413662,3.378699,11191.651176,3.930,4.401076,26.780779
189,Philippines,2022,8.288528,5.821158,3577.701366,2.598,54.477786,22.473718
190,Thailand,2022,6.176202,-1.610680,6278.785514,0.940,35.061350,26.308404
191,United States,2022,2.531839,8.002800,63886.131707,3.650,1.000000,18.692764

In [65]:
real_final_df.to_csv("real_final_df.csv",index=False)